import Head from "next/head";
import instaLogo from "../public/compLogo.png";
import Image from "next/image";
import { useFormik, Field } from "formik";
import * as Yup from "yup";
import Dropzone from "react-dropzone";
import render from "react-dom";

export default function Home() {
  const formik = useFormik({
    initialValues: {
      agent_name: "",
      agent_accountname: "",
      agent_email: "",
      agent_gender: "",
      marital_status: "",
      prime_number: "PI123456789",
      comp_name: "",
      business_address: "",
      agent_momonumber: "",
      business_nature: "",
      business_reg_number: "",
      primary_contact_name: "",
      primary_contact_number: "",
      primary_contact_email: "",
      secondary_contact_name: "",
      secondary_contact_number: "",
      secondary_contact_email: "",
      number_of_outlets: "0",
      image_upload: [],
      next_of_kin_name: "",
      next_of_kin_email: "",
      next_of_kin_mobile: "",
      terms: ""
    },

    validationSchema: Yup.object({
      agent_name: Yup.string()
        .max(20, "Name must at least 20 characters or less")
        .required("Name is required")
    }),

    onSubmit: (values) => {
      console.log(values);
    }
  });

  console.log(formik.values);

  return (
    <div>
      <Head>
        <title>InstaBusiness | Self Service Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" flex items-center justify-center  lg:mt-20 lg:mb-20">
        <form
          onSubmit={formik.handleSubmit}
          className="bg-white flex rounded-lg lg:w-1/2 md:w-4/5 font-sans border border-gray-100 "
        >
          <div className="flex-1 text-gray-700 p-20">
            <div className="flex justify-center " id="Logo">
              <Image src={instaLogo} alt="" className="h-[70px] w-[200px]" />
            </div>

            <h2 className="text-2xl flex justify-center p-3 font-medium ">
              Self Service Portal
            </h2>
            <p className="text-lg text-gray-500 flex justify-center">
              Fill the form below to request a loan for your business
            </p>

            <div>
              <h2 className="bg-blue-700 text-white px-2 mt-8">
                Agent Details
              </h2>
            </div>

            <div className="mt-6 grid md:grid-cols-2 lg:grid-cols-3 gap-4 md:items-center md:justify-center ">
              {/*agent details section */}

              <div className="pb-4" id="Agent Name">
                <label
                  htmlFor=" agent_name"
                  className="block font-opensans pb-2"
                >
                  Agent Name
                </label>
                <input
                  className="border-2 border-gray-500 rounded-md p-2 w-[250px] h-[40px] focus:border-blue-500 focus:ring-blue-500"
                  type="text"
                  name="agent_name"
                  placeholder="Enter agent name "
                  value={formik.values.agent_name}
                  onChange={formik.handleChange}
                />
              </div>
              <div className="pb-4" id="Account Name">
                <label
                  htmlFor=" agent_accountname"
                  className="block font-opensans pb-2"
                >
                  Account Name
                </label>
                <input
                  className="border-2 border-gray-500 rounded-md p-2 w-[250px] h-[40px] focus:border-blue-500 focus:ring-blue-500"
                  type="text"
                  name="agent_accountname"
                  placeholder="Enter account name "
                  value={formik.values.agent_accountname}
                  onChange={formik.handleChange}
                />
              </div>
              <div className="pb-4" id="P.I Account Number">
                <label
                  htmlFor="prime_number"
                  className="block font-opensans pb-2"
                >
                  Prime Invest Account Number
                </label>
                <input
                  className="border-2 border-gray-400 rounded-md p-2 w-[250px] h-[40px] focus:border-blue-500
                   focus:ring-blue-500"
                  type="text"
                  name="prime_number"
                  placeholder="Enter account number "
                  value={formik.values.prime_number}
                  onChange={formik.handleChange}
                />
              </div>
              <div className="pb-4" id="Company Name">
                <label
                  htmlFor="company name"
                  className="block font-opensans pb-2"
                >
                  Company Name
                </label>
                <input
                  className="border-2 border-gray-500 rounded-md p-2 w-[250px] h-[40px] focus:border-blue-500 focus:ring-blue-500"
                  type="text"
                  name="comp_name"
                  placeholder="Enter company name "
                  value={formik.values.comp_name}
                  onChange={formik.handleChange}
                />
              </div>
              <div className="pb-4" id="Business Address">
                <label
                  htmlFor=" business address"
                  className="block font-opensans pb-2"
                >
                  Business address
                </label>
                <input
                  className="border-2 border-gray-500 rounded-md p-2 w-[250px] h-[40px] focus:border-blue-500 focus:ring-blue-500"
                  type="text"
                  name="business_address"
                  placeholder="Enter business address "
                  value={formik.values.business_address}
                  onChange={formik.handleChange}
                />
              </div>
              <div className="pb-4" id=" Agent Email">
                <label htmlFor="email" className="block font-opensans pb-2">
                  Email address
                </label>
                <input
                  className="border-2 border-gray-500 rounded-md p-2 w-[250px] h-[40px] focus:border-blue-500 focus:ring-blue-500"
                  type="email"
                  name="agent_email"
                  placeholder="Enter email address "
                  value={formik.values.agent_email}
                  onChange={formik.handleChange}
                />
              </div>
              <div className="pb-4" id="Mobile Money Number">
                <label
                  htmlFor=" momo number"
                  className="block font-opensans pb-2"
                >
                  Mobile Money Number
                </label>
                <input
                  className="border-2 border-gray-500 rounded-md p-2 w-[250px] h-[40px] focus:border-blue-500 focus:ring-blue-500"
                  type="number"
                  name="agent_momonumber"
                  placeholder="Enter mobile money number "
                  value={formik.values.agent_momonumber}
                  onChange={formik.handleChange}
                />
              </div>
              <div className="pb-4" id="Nature of Business">
                <label
                  htmlFor=" nature of business"
                  className="block font-opensans pb-2"
                >
                  Nature of business
                </label>
                <input
                  className="border-2 border-gray-500 rounded-md p-2 w-[250px] h-[40px] focus:border-blue-500 focus:ring-blue-500"
                  type="text"
                  name="business_nature"
                  placeholder="Enter nature of business "
                  value={formik.values.business_nature}
                  onChange={formik.handleChange}
                />
              </div>
              <div className="pb-4" id="Number of outlets">
                <label
                  htmlFor=" number_of_outlets"
                  className="block font-opensans pb-2"
                >
                  Number Of Outlets
                </label>
                <select
                  value={formik.values.number_of_outlets}
                  onChange={formik.handleChange}
                  name="number_of_outlets"
                  className="border-2 border-gray-500 rounded-md p-2 w-[250px]
                  h-[40px] focus:border-blue-500 focus:ring-blue-500 md:mt-6 lg:mt-0"
                >
                  <option>0</option>
                  <option>1</option>
                  <option>2</option>
                  <option>3</option>
                </select>
              </div>
              <div className="pb-4" id="Registration Number">
                <label
                  htmlFor=" business registration number"
                  className="block font-opensans pb-2"
                >
                  Business registration number (Enclose a copy of certification)
                </label>
                <input
                  className="border-2 border-gray-500 rounded-md p-2 w-[250px] h-[40px] focus:border-blue-500 focus:ring-blue-500"
                  type="text"
                  name="business_reg_number"
                  placeholder="Enter business reg. number "
                  value={formik.values.business_reg_number}
                  onChange={formik.handleChange}
                />
              </div>
              <div className="pb-4 flex items-center" id="agent_gender">
                <div className="flex items-start">
                  <label
                    htmlFor=" Gender"
                    className="block font-opensans pb-2 mr-2"
                  >
                    Gender:
                  </label>
                  <div className="grid grid-cols-1" id="gender options">
                    <div className="flex items-center pb-5" id="male">
                      <input
                        className="border-2 border-gray-500 rounded-md p-2 mr-2 w-5 h-5 focus:border-blue-500 focus:ring-blue-500"
                        type="radio"
                        name="agent_gender"
                        value="male"
                        onChange={formik.handleChange}
                      />
                      <label htmlFor="male" className="mr-2">
                        Male
                      </label>
                    </div>
                    <div className="flex items-center" id="female">
                      <input
                        className="border-2 border-gray-500 rounded-md p-2 mr-2 w-5 h-5 focus:border-blue-500 focus:ring-blue-500"
                        type="radio"
                        name="agent_gender"
                        value="female"
                        onChange={formik.handleChange}
                      />
                      <label htmlFor="female">Female</label>
                    </div>
                  </div>
                </div>
              </div>
              <div className="pb-4 flex items-center" id="marital status">
                <div className="flex items-start">
                  <label
                    htmlFor=" Marriage Status"
                    className="block font-opensans pb-2 mr-2"
                  >
                    Marrital Status:
                  </label>
                  <div className="grid grid-cols-1" id="status options">
                    <div className="flex items-center pb-5" id="married">
                      <input
                        className="border-2 border-gray-500 rounded-md p-2 mr-2 w-5 h-5 focus:border-blue-500 focus:ring-blue-500"
                        type="radio"
                        name="marital_status"
                        value="Married"
                        onChange={formik.handleChange}
                      />
                      <label htmlFor="male" className="mr-2">
                        Married
                      </label>
                    </div>
                    <div className="flex items-center" id="female">
                      <input
                        className="border-2 border-gray-500 rounded-md p-2 mr-2 w-5 h-5 focus:border-blue-500 focus:ring-blue-500"
                        type="radio"
                        name="marital_status"
                        value="Single"
                        onChange={formik.handleChange}
                      />
                      <label htmlFor="female">Single</label>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/*Contact section */}
            <div>
              <h2 className="bg-blue-700 text-white px-2 mt-8"> Contacts</h2>
            </div>
            <div className="mt-6 grid lg:grid-cols-3 md:grid-cols-2 gap-4 ">
              <div className="pb-4" id="primary contact name">
                <label
                  htmlFor=" primary contact name"
                  className="block font-opensans pb-2"
                >
                  Primary Contact Name
                </label>
                <input
                  className="border-2 border-gray-500 rounded-md p-2 w-[250px] h-[40px] focus:border-blue-500 focus:ring-blue-500"
                  type="text"
                  name="primary_contact_name"
                  placeholder="Enter contact name "
                  value={formik.values.primay_contact_name}
                  onChange={formik.handleChange}
                />
              </div>
              <div className="pb-4" id="primary contact phone">
                <label
                  htmlFor=" Designation mobile number"
                  className="block font-opensans pb-2"
                >
                  Designation mobile number
                </label>
                <input
                  className="border-2 border-gray-500 rounded-md p-2 w-[250px] h-[40px] focus:border-blue-500 focus:ring-blue-500"
                  type="number"
                  name="primary_contact_number"
                  placeholder="Enter mobile number "
                  value={formik.values.primary_contact_number}
                  onChange={formik.handleChange}
                />
              </div>
              <div className="pb-4" id="primary contact email">
                <label htmlFor=" email" className="block font-opensans pb-2">
                  Email Address
                </label>
                <input
                  className="border-2 border-gray-500 rounded-md p-2 w-[250px] h-[40px] focus:border-blue-500 focus:ring-blue-500"
                  type="email"
                  name="primary_contact_email"
                  placeholder="Enter email address "
                  value={formik.values.primary_contact_email}
                  onChange={formik.handleChange}
                />
              </div>
              <div className="pb-4" id="secondary contact name">
                <label
                  htmlFor=" agent name"
                  className="block font-opensans pb-2"
                >
                  Secondary Contact Name
                </label>
                <input
                  className="border-2 border-gray-500 rounded-md p-2 w-[250px] h-[40px] focus:border-blue-500 focus:ring-blue-500"
                  type="text"
                  name="secondary_contact_name"
                  placeholder="Enter contact name "
                  value={formik.values.secondary_contact_name}
                  onChange={formik.handleChange}
                />
              </div>
              <div className="pb-4" id="secondary contact phone">
                <label
                  htmlFor=" Designation mobile number"
                  className="block font-opensans pb-2"
                >
                  Designation mobile number
                </label>
                <input
                  className="border-2 border-gray-500 rounded-md p-2 w-[250px] h-[40px] focus:border-blue-500 focus:ring-blue-500"
                  type="number"
                  name="secondary_contact_number"
                  placeholder="Enter mobile number "
                  value={formik.values.secondary_contact_number}
                  onChange={formik.handleChange}
                />
              </div>
              <div className="pb-4" id="secondary contact email">
                <label htmlFor=" email" className="block font-opensans pb-2">
                  Email Address
                </label>
                <input
                  className="border-2 border-gray-500 rounded-md p-2 w-[250px] h-[40px] focus:border-blue-500 focus:ring-blue-500"
                  type="email"
                  name="secondary_contact_email"
                  placeholder="Enter email address "
                  value={formik.values.secondary_contact_email}
                  onChange={formik.handleChange}
                />
              </div>
              <div className="pb-4" id="next_of_kin_name">
                <label htmlFor=" email" className="block font-opensans pb-2">
                  Next Of Kin
                </label>
                <input
                  className="border-2 border-gray-500 rounded-md p-2 w-[250px] h-[40px] focus:border-blue-500 focus:ring-blue-500"
                  type="text"
                  name="next_of_kin_name"
                  placeholder="Enter name "
                  value={formik.values.next_of_kin_name}
                  onChange={formik.handleChange}
                />
              </div>
              <div className="pb-4" id="next_of_kin_mobile">
                <label htmlFor=" email" className="block font-opensans pb-2">
                  Next Of Kin Mobile Number
                </label>
                <input
                  className="border-2 border-gray-500 rounded-md p-2 w-[250px] h-[40px] focus:border-blue-500 focus:ring-blue-500"
                  type="number"
                  name="next_of_kin_mobile"
                  placeholder="Enter mobile number"
                  value={formik.values.next_of_kin_mobile}
                  onChange={formik.handleChange}
                />
              </div>
              <div className="pb-4" id="next_of_kin_email">
                <label htmlFor=" email" className="block font-opensans pb-2">
                  Next Of Kin Email
                </label>
                <input
                  className="border-2 border-gray-500 rounded-md p-2 w-[250px] h-[40px] focus:border-blue-500 focus:ring-blue-500"
                  type="email"
                  name="next_of_kin_email"
                  placeholder="Enter email address "
                  value={formik.values.next_of_kin_email}
                  onChange={formik.handleChange}
                />
              </div>
            </div>

            {/*Declaration section */}
            <div>
              <h2 className="bg-blue-700 text-white px-2 mt-8 mb-4">
                Declaration (Terms of Service)
              </h2>
            </div>
            <div>
              <div className="pb-4 " id="terms">
                <div className="flex items-start gap-2">
                  <input
                    className="border-2 border-gray-500 rounded-md h-6 w-6 focus:border-blue-500 focus:ring-blue-500"
                    type="checkbox"
                    name="terms"
                    value="checked"
                    onChange={formik.handleChange}
                  />
                  <p>
                    I hereby agree to the terms and conditions herein stated and
                    do hereby certify that the information provided in this form
                    is true and accurate. I agree that InstaBusiness reserves
                    the right to take appropriate measures including legal
                    action if the information provided here is discovered to be
                    false. By signing this form I confirm that I have read,
                    received and agree to be bound by the Agent Service.”
                  </p>
                </div>
              </div>
            </div>

            {/*Buttons section */}
            <div>
              <input
                type="file"
                name="image_upload"
                multiple
                onChange={formik.handleChange}
                className="block w-full text-sm text-slate-500
                file:mr-4 file:py-2 file:px-4
                file:rounded-md file:border-0
                file:text-sm file:font-semibold
               file:bg-blue-50 file:text-blue-700
               hover:file:bg-blue-100 pb-6"
              />

              <button
                type="submit"
                className="bg-blue-700 text-sm text-white p-2  rounded-md w-full"
              >
                Submit
              </button>
            </div>
          </div>
        </form>
      </main>
    </div>
  );
}
