import Head from "next/head";
import instaLogo from "../public/compLogo.png";
import Image from "next/image";
import { useFormik, Formik, Field, Form } from "formik";
import { useRouter } from "next/router";
import { Button } from "@material-tailwind/react";
import axios from "axios";
import { useState } from "react";
import LocalStorageService from "./api/token";

const LoginPage = () => {
  const [merchantNumber, setMerchantNumber] = useState("");
  const [password, setPassword] = useState("");

  const router = useRouter();

  const handleLogin = async (e) => {
    e.preventDefault();

    // Prepare request headers
    const headers = {
      Authorization: "Token " + LocalStorageService.getAccessToken(),
      "Content-Type": "application/json",
      Accept: "application/json"
    };

    // Prepare request body
    const body = JSON.stringify({
      merchantNumber,
      password
    });

    try {
      const response = await axios.fetch(
        "https://apiib.newvifinancial.com/users/token/",
        {
          method: "POST",
          headers,
          body
        }
      );

      if (response.ok) {
        const data = await response.json();

        // Store the token in localStorage
        localStorage.setItem("/api/token", data.token);

        // Redirect to the next page
        // Use Next.js router to navigate to the desired page
        // router.push("/loanForm");
        res.status(200).json({ message: "Login successful" });
        router.push({ pathname: "/loanForm", query: values });
      } else {
        // Handle failed login attempt
        res.status(401).json({ message: "Invalid credentials" });
      }
    } catch (error) {
      // Handle network or API error
    }
  };

  return (
    <div className="flex ml-5 md:mr-5 items-center justify-center">
      <Head>
        <title>InstaBusiness | Loan Request</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex items-center min-w-max lg:w-[800px] justify-center">
        <div className="flex min-h-full flex-1 flex-col justify-center m-40 px-6 py-12 lg:px-8 bg-white border border-gray-400 rounded-md shadow-lg">
          <div id="signin" className="">
            <div className="flex justify-center " id="Logo">
              <Image src={instaLogo} alt="" className="h-[50px] w-[150px]" />
            </div>
            <h2 className="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">
              Sign in to your account
            </h2>
          </div>

          <div className="mt-10 sm:mx-auto sm:w-full sm:max-w-sm ">
            <form className=" space-y-6" onSubmit={handleLogin}>
              <div id="merchant-number" className="relative">
                <input
                  type="number"
                  name="merchant_number"
                  autoComplete="number"
                  id="floating_merchant_number"
                  value={merchantNumber}
                  onChange={(e) => setMerchantNumber(e.target.value)}
                  className="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-white rounded-lg border border-gray-300 appearance-none  dark:border-gray-400 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                  placeholder=" "
                  required
                />
                <label
                  htmlFor="floating_outlined"
                  className="absolute text-sm text-gray-900 dark:text-gray-900 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-white px-2 peer-focus:px-2 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1"
                >
                  Merchant Number
                </label>
              </div>

              <div id="password">
                <div id="password_" className="relative mb-2">
                  <input
                    type="password"
                    name="password"
                    autoComplete="password"
                    id="floating_password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    className="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-white rounded-lg border border-gray-300 appearance-none  dark:border-gray-400 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                    placeholder=" "
                    required
                  />
                  <label
                    htmlFor="floating_outlined"
                    className="absolute text-sm text-gray-500 dark:text-gray-900 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-white px-2 peer-focus:px-2 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1"
                  >
                    Insta Pin
                  </label>
                </div>
                <div id="forgot_pass" className="flex items-end justify-end">
                  <div className="text-sm " id="forgot_pass">
                    <a
                      href="#"
                      className="font-semibold text-blue-600 hover:text-blue-500"
                    >
                      Forgot password?
                    </a>
                  </div>
                </div>
              </div>

              <div id="sign_in">
                <Button
                  type="submit"
                  className="flex w-full justify-center rounded-md bg-blue-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-blue-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600"
                >
                  Sign in
                </Button>
              </div>
            </form>
          </div>
        </div>
      </main>
    </div>
  );
};

export default LoginPage;
